apiVersion: v1
kind: ConfigMap
metadata:
  name: static-site
  labels:
    app: static-site
data:
  upcloud_obj_endpoint: "${UPCLOUD_OBJ_ENDPOINT}"
  upcloud_obj_id: "${UPCLOUD_OBJ_ID}"
  upcloud_obj_secret: "${UPCLOUD_OBJ_SECRET}"